# Generated by Django 5.2.7 on 2026-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_prefix',
            field=models.CharField(default='+1', max_length=8),
        ),
    ]
